### ISSUE TITLE
[Evolution] maximum credits?

### ISSUE THREAD

**Issue by pordino** [NeuroAssassin/Toxic-Cogs#12]
Playing the game for a while it seems to have stopped giving more credits when user balance reached 8,542,672 credits
Trying another game (casino) shows that the balance can still be increased (and the maximum balance is some gazillion or something).

Is there a way to adjust this? I've had a quick look but I couldn't find it yet.

**Comment by NeuroAssassin** [comment]
Hi there!  Thanks for using my cogs and taking the time to creating an issue!  Unfortunately, looking at the code, I'm not sure if this is an error with my cog.  If you could, please check out the command `[p]bank set maxbal` to see if that might be the issue.

**Comment by NeuroAssassin** [comment]
If this issue continues to persist, feel free to reopen it.

**Comment by pordino** [comment]
Yeah it's a bit weird. The maxbal had been set to 9,000,000,000,000,000,000 so there was 'some' room to grow :P.

After buying new animals I had way less (~200K credits) and then it was stuck on that (so not going up from the 200K for a couple hours).
Restarting the red service seems to have solved it. Bit sad, now I don't know what it was (no errors I could see).

Anyway thanks for your time!
