### ISSUE TITLE
[Maintenance] Bot doesn't respond after Update

### ISSUE THREAD

**Issue by theMisteryDE** [NeuroAssassin/Toxic-Cogs#16]
Hey, I just updated my Bot while in activated Maintenance. After that my Bot doesn't even respond to my commands. Could only shut it down and delete the repo folder. 

My issue could be found, with screenshot of the last line, in Support Server:
https://discordapp.com/channels/133049272517001216/387398816317440000/715742194526584885

**Comment by NeuroAssassin** [comment]
Fixed, thanks for reporting!
