### ISSUE TITLE
[Scanner] suggestion for whitelist

### ISSUE THREAD

**Issue by theMisteryDE** [NeuroAssassin/Toxic-Cogs#17]
Since I'm already on your repo, I wanna make a suggestion for the scanner cog. I really like how good it works, but I would like to whitelist my NSFW Channels. Do you think this is possible?

**Comment by NeuroAssassin** [comment]
Should be possible, I'll look into it.

**Comment by NeuroAssassin** [comment]
Just added whitelist and blacklist functionality.  Thanks for the suggestion.
