### ISSUE TITLE
[UpdateChecker] Update can't actually happen

### ISSUE THREAD

**Issue by PhasecoreX** [NeuroAssassin/Toxic-Cogs#2]
Based on your cog creator application, it looks like you removed the `[p]cogupdater all` command, as you didn't need it anymore. However, `bg_task` is still checking if that command was ran once (checking if the config value `updated` is true), so nothing ever updates. [Line 45 and 46](https://github.com/NeuroAssassin/Toxic-Cogs/blob/fc76e9a02d901051d6d8592fe1ef4e8e201fd7f8/updatechecker/updatechecker.py#L45) would have to be removed for it to work again as far as I know. Also that default config value wouldn't be needed anymore.

Also, just a suggestion, if you could have the check time configurable, that would be great! Or at least have it set to 5 minutes or something. I don't really want to have Github hit every 60 seconds for each repo. Seems like overkill. I can make a new issue for it if you want.

**Comment by NeuroAssassin** [comment]
Hey there @PhasecoreX, thanks for making this issue.  I'll try to fix it as soon as possible, but I am unsure of how long it will take.  Thanks for bringing it to my attention.

**Comment by NeuroAssassin** [comment]
Forgot to mark this issue as fixed
