### ISSUE TITLE
[Scanner] Updates and new features

### ISSUE THREAD

**Issue by LillyCosmo** [NeuroAssassin/Toxic-Cogs#41]
The scanner is a little outdated, I would like to request to add to it text moderation in images, as well as all of the features in text moderation.

**Comment by Drapersniper** [comment]
Oh nice, that's an awesome idea although I suspect you are going to be compensating @NeuroAssassin for this time here right or create a PR yourself?

I mean after all you seem to know your stuff so creating a PR would be mighty helpful with your less outdated scanner, alternatively if you are too busy there's nothing neuro will not do for Money. If you don't have money don't worry for a limited time offer Neuro will update his cog to your exact expectations for the low low price of a 3090 strix and a 5950x.

Alternatively alternatively you could maybe pay attention to how you come across to people,  could start by not insulting peoples work and not coming across like you are demanding people to work for you for free.

**Comment by NeuroAssassin** [comment]
Hello, thanks for making this issue.  I started looking into this, but unfortunately, this would require a large cog redo (as it nearly doubles the cog size at least), while to put it blunt, I don't have much time for projects that are not monetarily beneficial, other than Dashboard which all that free time goes towards.  That said, if you want to arrange some sort of deal where you make an offer of compensation for my time, feel free to contact me.

**Comment by LillyCosmo** [comment]
I apologize for the little day and understand! What sort of price range were you looking at to do this?

**Comment by NeuroAssassin** [comment]
Hey there!  Let's move this to Discord DMs as that would be more suitable.  You can contact me at Neuro Assassin#4779.

**Comment by LillyCosmo** [comment]
Sounds good!
