### ISSUE TITLE
[deleter] wishlist: please support option to ignore pinned messages

### ISSUE THREAD

**Issue by synrg** [NeuroAssassin/Toxic-Cogs#43]
If `deleter` cog ignored pinned messages (like `[p]cleanup` does) then it would make it less of a hassle to keep selected messages.

Use case:

- I have a personal channel on my private server for conversations with one particular friend.
- We have set the channel deletion period to 24hrs because we don't want Discord to permanently keep these personal conversations.
- We would like an effortless way to keep certain messages for longer than the 24hr deletion period, and an equally effortless way to finally remove them once they're no longer relevant.
- We like how simple pins are and would like to do it that way.
- We both have permission to pin messages to the channel.

We currently have to use `[p]deleter remove <id#>` but:

- It doesn't have single-click simplicity.
- It has low visibility (aside from the fact that the messages don't automatically get deleted - but they are otherwise indistinguishable from other more recent messages) vs. pins are always viewable separately.

Pins would solve both of these issues if `deleter` could be configured to ignore them.

**Comment by synrg** [comment]
Actually, I have tried pins and manual `cleanup messages 100` for a few weeks now, and me and my conversational partner have gotten used to it. I think I actually prefer it over what I suggested. If you feel it's worth retaining as a wishlist, go ahead. Or if you have no intention to implement it, feel free to close it. We no longer need this.

**Comment by NeuroAssassin** [comment]
Huh, I somehow completely missed this issue.  I have received this request a lot so I've been looking to implement it, just haven't had much time to implement it however.  Thanks for your feedback though, let me know if you have any more questions.

**Comment by synrg** [comment]
I found a different use case. We're using Trivia cog now on a `#trivia` channel on a large server I admin, and have deleter set to delete messages after 24h. It would be nice if additional instructions could be put in pinned messages.

**Comment by NeuroAssassin** [comment]
I realize I never updated this issue, but Deleter no longer deletes pinned messages from commit d132973.
