### ISSUE TITLE
[Evolution] Abusable race conditions 

### ISSUE THREAD

**Issue by Flame442** [NeuroAssassin/Toxic-Cogs#5]
Evolution has lots of race conditions based on how config is handled. The most obvious of them all is the following situation:
1. Start with 2 animals of a specific level.
2. Begin a purchase of more animals with `[p]evolution buy`.
3. Before confirming the purchase, evolve your two animals.
4. Complete the purchase. You now have the animals you just bought as well as the animals you had evolved.

Config handling needs a rework.

**Comment by NeuroAssassin** [comment]
i got lazy and did this.  finally fixed after... 7 months
