### ISSUE TITLE
Maintenance double maintenance message

### ISSUE THREAD

**Issue by brysonchase43** [NeuroAssassin/Toxic-Cogs#57]
Can you please fix your maintenance cog? It keeps sending the maintenance message 2 times. I do not have 2 instances running. 

![](https://cdn.discordapp.com/attachments/803040188620079116/847231840581451786/image0.png)

**Comment by NeuroAssassin** [comment]
What part of the phrase "not welcome here" do you not understand?

Every single person that you have contacted after being banned has made it exceptionally clear that they wish for no contact from you.  And yet you still continue to feel the need to be so desperate for attention, so bothersome, so ignorant, so aggravating, so annoying and so arrogant that you decide that you are above that and to reach out again?  I, as well as many other creators have made it clear that we wish no contact from you whatsoever.  And you continue to break this agreement.

I thought that after interacting with Draper and the conversation that took place there would finally make a impact on your head, given the clear agreement that was made, and the clear consequences that would occur if you came near any of us with any of your alts every again.  But guess what, you chose to take that one chance you had, crumbled into a paper ball and threw it into the toilet.

Let me make this clear.  I will be reporting you to Discord, Github and any other associated platforms that I find related to you in, filed from harassment.  You have done nothing but throw tantrums and do whatever the hell you want, with no thought as to who this affects or how annoying it is, and it's gone too far.  You've been warned MULTIPLE times, by cog creators, server staff and other members of the server.  You have been banned multiple times from cog servers and it has been made clear to you that you are unwelcome.  You've been told to stay away in the name of legal consequences.  Be glad that I'm currently only reporting you to online platforms (however I will not say the same of others).  But attempt to interact with me again, and expect there to be legal action.  Mark my fucking words.
