### ISSUE TITLE
[Reacticket] Add autonomous confirmation setting to archive prune

### ISSUE THREAD

**Issue by EternalllZM** [NeuroAssassin/Toxic-Cogs#63]
When using the command
`reacticket settings closesettings prune`
it requires confirmation on the end of the bot owner to purge these channels.
This prevents the automated purging via a scheduler or similar automation cog. 

My proposal is a sub command `reacticket settings closesettings prune yes` that will not prompt the usual _"Are you sure you want to remove all archived ticket channels?"_ and immediately purge all ticket channels without asking beforehand.

**Comment by NeuroAssassin** [comment]
Feature implemented in #64
